services:
  frontend:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - mediamtx

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "9997:9997" # API
      - "8888:8888" # HLS
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8889:8889" # WebRTC
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
